spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: wir-social-maintenance
                port:
                  number: 80